global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Pour surveiller Prometheus lui-même

  - job_name: "nodejs_app"
    static_configs:
      - targets: ["host.docker.internal:3000"] # Application Node.js sur le port 3000
